### PR TITLE
Adds Site level StandardImagesSizes

### PR DESCRIPTION
**Pull request by Ryan-Anderson**

### CODE REVIEW

**Comment by iamedu** [comment]
+1

**Comment by Ryan-Anderson** [comment]
As it stands right now, the StandardImageSizes can be referenced by multiple sites. We need a different approach to ensure unique displayNames/internalNames with multiple Site references.

**Comment by Ryan-Anderson** [comment]
Will reopen once I resolve a few issues

**Comment by Ryan-Anderson** [comment]
Closing this in favor of different implementation.

**Pull request closed without merging**
